Repository codestates-seb/seb40_main_036, pull requests merged in 2022-11, with the labels that each got.

#16 11.15 merge 합니다
  client/public/index.html
  client/src/App.js
  client/src/components/Map.js
  client/src/components/ShareList.js
  client/src/components/SideNav.js
  client/src/components/button.js
  client/src/components/nav.js
  client/src/img/locationDotSolid.svg
  client/src/pages/main.js
  client/src/static/Incheon.json
Labels: [FE]김지연

#17 11.15 머지
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/AnswerPost.js
  client/src/components/EarthquakeTipsContents.js
  client/src/components/EvacuationTips.js
  client/src/components/ShareAnswerViewr.js
  client/src/components/ShareList.js
  client/src/components/ShareListViewer.js
  client/src/components/ShareListViewerContents.js
  client/src/components/pagination.js
  client/src/img/profile.png
  client/src/img/상황별행동요령.jpeg
  client/src/img/장소별행동요령.jpeg
  client/src/pages/ShareListLookup.js
Labels: [FE]성유미

#40 [Client] 회원가입 로그인 로그아웃 구현 완료 (일단 세션 스토리지)
  client/src/App.js
  client/src/components/Editor.js
  client/src/components/Login.js
  client/src/components/LogoutNav.js
  client/src/components/SignUp.js
  client/src/setupProxy.js
Labels: [FE]이철재

#69 [Client] 글작성 구현 완료 글 수정은 틀만
  client/package-lock.json
  client/package.json
  client/src/components/Dropdown.js
  client/src/components/Editor.js
  client/src/components/ShareListViewerContents.js
  client/src/components/SignUp.js
  client/src/components/WriteForm.js
  client/src/components/WriteUpdate.js
  client/src/setupProxy.js
Labels: [FE]이철재
